// The 65 tests on the Agilus "CC SPRF" price list - these are the tests
// doctors prescribe most frequently, so they lead the default (no-query)
// listing in the search modal's Tests tab and the "All Tests" page.
//
// Order reflects prescribing frequency in Indian general/gynaecological
// practice (most-ordered first): routine health-checkup panels (CBC, urine
// routine, lipid, liver, kidney, HbA1c, thyroid, Vitamin D/B12) lead, then
// common standalone/monitoring tests, then fertility and antenatal workups,
// then more specialised or infrequently-ordered tests.
export const CC_SPRF_TEST_SLUGS = [
  "cbc-5-edta-whole-blood",
  "urinalysis",
  "lipid-profile-serum",
  "liver-function-profile-serum",
  "kidney-function-test",
  "glycosylated-hemoglobin-hba1c",
  "tsh-3rd-gen-ultrasensitive-serum",
  "vitamin-d-total-25-hydroxyvitamin-d-serum",
  "vitamin-b12-cyanocobalamine-serum",
  "hemoglobin-by-cyanmethaemoglobin",
  "creatinine-serum",
  "c-reactive-protein-crp-serum-quantitative",
  "erythrocyte-sedimentation-rate-esr",
  "electrolytes-na-k-cl-serum",
  "calcium-serum",
  "uric-acid-serum",
  "blood-urea-nitrogen-bun-serum",
  "alanine-aminotransferase-alt-sgpt-serum",
  "aspartate-aminotransferase-ast-sgot-serum",
  "bilirubin-total-direct-indirect-serum",
  "abo-group-rh-type-edta-whole-blood",
  "platelet-count-edta-whole-blood",
  "widal-test-serum",
  "hcg-serum",
  "culture-urine-with-susceptibility",
  "cbc-with-esr-cbcpsesr",
  "stool-ova-parasite",
  "serum-iron-and-tibc-studies",
  "triglycerides-serum",
  "cholesterol-serum",
  "rheumatoid-factor-serum",
  "prothrombin-time-pt-inr-citrate-plasma",
  "activated-partial-thromboplastin-time-aptt",
  "free-thyroxine-ft4-serum",
  "free-triiodothyronine-ft3-serum",
  "thyroid-panel-tsh-serum",
  "thyroid-panel-ii-ft3-ft4-tsh-serum",
  "hiv-antibodies-serum",
  "hepatitis-b-surface-antigen-serum",
  "hcv-antibodies-serum",
  "bilirubin-direct-serum",
  "double-marker-test-serum",
  "torch-igg-igm-evaluation-serum",
  "lh-fsh-prolactin-serum",
  "follicle-stimulating-hormone-fsh-serum",
  "luteinizing-hormone-lh-serum",
  "prolactin-serum",
  "amh-mis-serum",
  "estradiol-e2-serum",
  "testosterone-total-serum",
  "anti-nuclear-antibody-ana-ifa-serum",
  "quadruple-marker-test-serum",
  "insulin-fasting-serum",
  "hemoglobin-variant-analysis-blood",
  "homocysteine-serum-plasma",
  "total-ige-serum",
  "torch-igg-evaluation-serum",
  "torch-igm-5-parameters",
  "prostate-specific-antigen-psa-serum",
  "ca-125-ovarian-cancer-monitor-serum",
  "alpha-fetoprotein-afp-serum",
  "mycoreal",
  "lymphocyte-subset-enumeration-blood",
  "blood-lympho-culture",
  "small-tissue-biopsy",
] as const;
